name: 'Submodule Commit Hash'
description: 'To hash the commit of the submodule for cache purposes'
inputs:
  path:
    description: 'Path to the submodule'
    required: true
    default: './'
outputs:
  sha256:
    description: "Submodule's commit hash"
    value: ${{ steps.Submodule-Version-Hash-Action.outputs.sha256 }}
runs:
  using: "composite"
  steps:
    - name: Submodule Hash
      id: submodule-hash
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/hash.sh ${{ inputs.path }}
        echo "sha256=$(${GITHUB_ACTION_PATH}/hash.sh ${{ inputs.path }})" >> $GITHUB_ENV
