name: 'Submodule Commit Hash'
description: 'To hash the commit of the submodule for cache purposes'
inputs:
  path:
    description: 'Path to the submodule'
    required: true
    default: './'
outputs:
  sha256:
    description: "Submodule's commit hash"
    value: ${{ steps.Submodule-Version-Hash-Action.outputs.sha256 }}
runs:
  using: "composite"
  steps:
    - name: Submodule Hash
      id: submodule-hash
      working-directory: ${{ inputs.path }}
      run: echo "sha256=$(( git submodule > hash.txt ) | certutil -hashfile hash.txt SHA256 | findstr /v "hash")"
